from typing import Any, Dict, NotRequired, Optional, TypedDict

class AnalyticsState(TypedDict):
    round_data: Dict[str, Any]          # Fetched via MCP (RoundAnalyticsResult)
    org_context: Dict[str, Any]         # Staff count, school type, etc.
    interpretations: Dict[str, Any]     # Generated by Psychologist Agent
    generation_provenance: NotRequired[Dict[str, Any]]
    recommendations: Dict[str, Any]     # Fetched by the local intervention catalog node
    safety_status: str                  # 'pass', 'fail', 'privacy_locked', 'provider_unavailable'
    safety_feedback: Optional[str]      # Reason for fail if safety validator rejects
    provider_failure_reason: NotRequired[str]  # Transport reason behind 'provider_unavailable'
    retry_count: int                    # Circuit breaker counter for safety loop
    final_payload: Dict[str, Any]       # Formatted Stone Map JSON payload
