from typing import TypedDict, Dict, Any, Optional

class AnalyticsState(TypedDict):
    round_data: Dict[str, Any]          # Fetched via MCP (RoundAnalyticsResult)
    org_context: Dict[str, Any]         # Staff count, school type, etc.
    interpretations: Dict[str, Any]     # Generated by Psychologist Agent
    recommendations: Dict[str, Any]     # Fetched by the local intervention catalog node
    safety_status: str                  # 'pass', 'fail', 'privacy_locked'
    safety_feedback: Optional[str]      # Reason for fail if safety validator rejects
    retry_count: int                    # Circuit breaker counter for safety loop
    final_payload: Dict[str, Any]       # Formatted Stone Map JSON payload
